### ISSUE TITLE
Rate limit requests?

### ISSUE THREAD

**Issue by fardeem** [smol-ai/developer#1]
SUPER FUN PROJECT! 

Ran it using the following prompt:

```
a flask app that serves a react frontend powered by create-react-app 
and also includes authentication. The react app should have a login
form and a page that is only accessible when you login in.
```

Errors out with 

```
Rate limit reached for default-gpt-4 in organization org-<> on tokens 
per min. Limit: 40000 / min. Please try again in 1ms. Contact us through 
our help center at help.openai.com if you continue to have issues.
```

How can we rate limit it? I'm not entirely sure how Modal fits into this and parallelizes it.

**Comment by fardeem** [comment]
I took out all the modal stuff and it's working but it's super slow. Working with the modal team to figure out why I'm running into issues.

**Comment by sw-yx** [comment]
thank you! yea i commented it out but the rate limiting can be controlled by the concurrency kwarg in main.py. hope the modal team sort that out! i really dont want to handle any of this stuff myself

good prompt! would maybe make a section for prompt ideas

**Comment by fardeem** [comment]
I figured out my issue here. Had nothing to do with modal. The files it would wanna generate would be like `flask_app/config.py` and the `write_file` function would fail since the directory didn't exist. Submitting PR to fix.
