### ISSUE TITLE
provide a devcontainer.json file for use with Codespaces and other VM IDEs

### ISSUE THREAD

**Issue by markgoho** [smol-ai/developer#24]
Not everyone is familiar with the local runtime needs of Python. In order to make running this CLI locally easier, provide a devcontainer.json. This file describes a local environment and essentially makes running the code a 1-step process.

**Comment by swyxio** [comment]
ah i see you added #30  for this

can you also add instructions to the readme? thank you!

**Comment by swyxio** [comment]
merged
