### ISSUE TITLE
Plugins/extensions

### ISSUE THREAD

**Issue by Joseph94m** [smol-ai/developer#32]
I saw that OpenAI just released ChatGPT plugins to everyone.
This includes: wolfram alpha, browsing, ambition, zapier....

I've been using smol-ai for a few days and I think it's awesome. 
Are there any plans to integrate plugins in the project (is it even possible to access these features through the API?)

Do you need help with that?

Cheers //

**Comment by swyxio** [comment]
thanks  for the idea! no, not right now, but i'm loooking at [Voyager](https://voyager.minedojo.org/) to do some skill library stuff...
