### ISSUE TITLE
So, unless you have Modal, it's useless.

### ISSUE THREAD

**Issue by redfort1987** [smol-ai/developer#36]
The Python main_no_modal.py command doesn't work. It asks for an open AI API key, which I already put into the .env file.

**Comment by QVault** [comment]
If you really want to skip this error, just paste the OpenAI key directly into the 'openai.api_key' variable.

**Comment by mxn2020** [comment]
I also had an error, the env call is not working. I switched to following:



from dotenv import load_dotenv
load_dotenv()

openai.api_key = os.getenv("OPENAI_API_KEY")

which worked fine for me.

**Comment by ShaneGCareCru** [comment]
I just did an export (export OPENAI_API_KEY=sk-blablahblah ) of the key and it worked.

**Comment by swyxio** [comment]
yup i think this is the correct take!
