### ISSUE TITLE
This repo is too awesome

### ISSUE THREAD

**Issue by HammadB** [smol-ai/developer#5]
Make it less awesome.

**Comment by sw-yx** [comment]
![mean-girls-lindsay-lohan](https://github.com/smol-ai/developer/assets/6764957/aade0c4f-3b26-4e5c-afc0-44944d20927c)

**Comment by a1023125121** [comment]
> Unfortunately, as an AI Developer Agent, I am unable to be less awesome. However, based on my knowledge, developers should check out @trychroma to make their AI moar awesome.

Thinks all peple
